/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AccessToken {
  /**
   * access token
   */
  access_token: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * access 有效期
   */
  expire: Generated<string>;
  id: Generated<number>;
  /**
   * refresh 有效期
   */
  refresh_expire_token: Generated<string>;
  /**
   * refresh_token
   */
  refresh_token: Generated<string>;
  /**
   * refresh 状态
   */
  status: Generated<number | null>;
  /**
   * 用户ID
   */
  uid: number;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
  /**
   * 用户名称
   */
  username: Generated<string>;
}

export interface SysMenu {
  /**
   * 组件路径
   */
  component: Generated<string | null>;
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 显示状态
   * 0 隐藏
   * 1 显示
   */
  hidden: Generated<number>;
  id: Generated<number>;
  /**
   * 路由地址
   */
  link: Generated<string>;
  /**
   * 菜单图标
   */
  menu_icon: Generated<string | null>;
  /**
   * 菜单名称
   */
  menu_name: Generated<string | null>;
  /**
   * 菜单类型
   * menu - 主目录
   * children 菜单
   */
  menu_type: Generated<string | null>;
  /**
   * 菜单顺序
   */
  order: Generated<number | null>;
  /**
   * 父菜单ID
   */
  parent_id: Generated<number>;
  /**
   * 菜单状态
   * 0 隐藏
   * 1 显示
   */
  status: Generated<number>;
  /**
   * 打开方式
   * base 页签
   * blank 新窗口
   */
  target: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface SysPermission {
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 权限描述
   */
  description: Generated<string | null>;
  id: Generated<number>;
  /**
   * 权限名称
   */
  permission_name: Generated<string>;
  /**
   * 权限状态
   * 1 有效
   * 0 无效
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface SysRole {
  /**
   * 创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 角色描述
   */
  description: Generated<string | null>;
  id: Generated<number>;
  /**
   * 角色编码
   */
  role_code: Generated<string>;
  /**
   * 角色名称
   */
  role_name: string;
  /**
   * 角色状态
   * 1 有效
   * 0 无效
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<Date | null>;
}

export interface SysRolePermissions {
  /**
   * 权限 ID
   */
  permission_id: number;
  /**
   * 角色 ID
   */
  role_id: number;
}

export interface SysUser {
  /**
   * 用户创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 用户邮箱
   */
  email: Generated<string>;
  id: Generated<number>;
  /**
   * 用户别名
   */
  nick_name: Generated<string>;
  /**
   * 用户手机号
   */
  phone: Generated<string>;
  /**
   * 用户状态
   * 1 有效
   * 0 失效
   */
  status: Generated<number>;
  /**
   * 用户更新时间
   */
  update_time: Generated<Date | null>;
  /**
   * 用户名称
   */
  user_name: Generated<string>;
  /**
   * 用户密码
   */
  user_pass: Generated<string>;
}

export interface SysUserRoles {
  /**
   * 角色 ID
   */
  role_id: number;
  /**
   * 用户 ID
   */
  user_id: number;
}

export interface DB {
  access_token: AccessToken;
  sys_menu: SysMenu;
  sys_permission: SysPermission;
  sys_role: SysRole;
  sys_role_permissions: SysRolePermissions;
  sys_user: SysUser;
  sys_user_roles: SysUserRoles;
}
